import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "./components/buttons";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body >
        <div className="black-drop"> 
        <header><Button text="Logar" /></header>
        {children}
        <footer><h1>Footer</h1></footer>
        </div>
      </body>
    </html>
  );
}
