

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "./components/buttons";
import { Header } from "./components/Header";
import { Modal } from "./components/Modal";
import { ModalContext, ModalProvider } from "./provider";
import { useContext } from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="pt-br">
      <ModalProvider>
        <body>

          <div className="black-drop"> 
            <Header /> 
            {children}
            <footer><h1>Footer</h1></footer>
          </div>
        
        </body>
      </ModalProvider>
    </html>
  );
}
